/**
 * Private parent-process IPC protocol used by the Electron directory-picker
 * provider. Both processes validate every received message before using it.
 * @module @deepseek-ai/dsh-host-directory-picker-electron/protocol
 */

import type { Branded } from '@deepseek-ai/dsh-brand'

/** Correlation id of one Electron directory-picker request. */
export type ElectronDirectoryPickerRequestId = Branded<'ElectronDirectoryPickerRequestId'>

/**
 * Brand a validated non-empty request id.
 * @param value - request id generated by a trusted endpoint or read from a validated message.
 * @returns the branded request id.
 */
export function electronDirectoryPickerRequestId(value: string): ElectronDirectoryPickerRequestId {
  if (value.trim() === '') throw new TypeError('Electron directory-picker request id must not be blank')
  return value as ElectronDirectoryPickerRequestId
}

/** Child asks the Electron parent to open one directory chooser. */
export interface ElectronDirectoryPickerRequestMessage {
  type: 'dsh/electron-directory-picker/request'
  requestId: ElectronDirectoryPickerRequestId
}

/** Child abandons one outstanding chooser request. */
export interface ElectronDirectoryPickerCancelMessage {
  type: 'dsh/electron-directory-picker/cancel'
  requestId: ElectronDirectoryPickerRequestId
}

/** Parent reports the absolute path chosen by the operator. */
export interface ElectronDirectoryPickerPickedMessage {
  type: 'dsh/electron-directory-picker/picked'
  requestId: ElectronDirectoryPickerRequestId
  path: string
}

/** Parent reports that the operator dismissed the chooser. */
export interface ElectronDirectoryPickerCancelledMessage {
  type: 'dsh/electron-directory-picker/cancelled'
  requestId: ElectronDirectoryPickerRequestId
}

/** Parent reports an actionable chooser failure. */
export interface ElectronDirectoryPickerFailedMessage {
  type: 'dsh/electron-directory-picker/failed'
  requestId: ElectronDirectoryPickerRequestId
  message: string
}

/** Messages sent from the web-host child to its Electron parent. */
export type ElectronDirectoryPickerChildMessage =
  | ElectronDirectoryPickerRequestMessage
  | ElectronDirectoryPickerCancelMessage

/** Messages sent from the Electron parent to its web-host child. */
export type ElectronDirectoryPickerParentMessage =
  | ElectronDirectoryPickerPickedMessage
  | ElectronDirectoryPickerCancelledMessage
  | ElectronDirectoryPickerFailedMessage

/** A string-keyed record suitable for exact IPC field validation. */
function record(value: unknown): Record<string, unknown> | undefined {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : undefined
}

/** Whether a value is a non-blank string. */
function nonBlankString(value: unknown): value is string {
  return typeof value === 'string' && value.trim() !== ''
}

/** Whether the record contains exactly the named own enumerable fields. */
function exactKeys(value: Record<string, unknown>, expected: readonly string[]): boolean {
  const actual = Object.keys(value)
  return actual.length === expected.length && expected.every(key => Object.hasOwn(value, key))
}

/**
 * Validate one child-to-parent message, including its exact field set.
 * @param value - untrusted value received from the Node IPC channel.
 * @returns whether the value is a recognized child message.
 */
export function isElectronDirectoryPickerChildMessage(value: unknown): value is ElectronDirectoryPickerChildMessage {
  const candidate = record(value)
  if (candidate === undefined || !nonBlankString(candidate.requestId)) return false
  switch (candidate.type) {
    case 'dsh/electron-directory-picker/request':
    case 'dsh/electron-directory-picker/cancel':
      return exactKeys(candidate, ['type', 'requestId'])
    default:
      return false
  }
}

/**
 * Validate one parent-to-child message, including its exact field set.
 * @param value - untrusted value received from the Node IPC channel.
 * @returns whether the value is a recognized parent message.
 */
export function isElectronDirectoryPickerParentMessage(value: unknown): value is ElectronDirectoryPickerParentMessage {
  const candidate = record(value)
  if (candidate === undefined || !nonBlankString(candidate.requestId)) return false
  switch (candidate.type) {
    case 'dsh/electron-directory-picker/picked':
      return exactKeys(candidate, ['type', 'requestId', 'path']) && nonBlankString(candidate.path)
    case 'dsh/electron-directory-picker/cancelled':
      return exactKeys(candidate, ['type', 'requestId'])
    case 'dsh/electron-directory-picker/failed':
      return exactKeys(candidate, ['type', 'requestId', 'message']) && nonBlankString(candidate.message)
    default:
      return false
  }
}
